# snake file to run the pipeline
# run python3 ./fit_dispersion.py

# define rule to fit dispersion relation
rule fit_correlator:
    input:
        "../../data/dispersion_data/d000_energy.jack",
        "../../data/dispersion_data/d001_energy.jack",
        "../../data/dispersion_data/d011_energy.jack",
        "../../data/dispersion_data/d111_energy.jack",
    output:
        "dispersion_pion.pdf"
    shell:
        "./run_dispersion.sh"

# define default rule
rule all:
    input:
        "dispersion_pion.pdf"

# define a rule to cleanup
rule clean:
    shell:
        "rm -f fit_dispersion.log dispersion_pion.pdf"