# snake file to run the pipeline
# run python3 ./fit_correlator.py --ini inis/input_x.ini && touch tag/input_x.tag
# for each input_x.ini in inis/

import os
import glob
# list all files in inis subdir
ini_files = glob.glob("inis/*.ini")
print(ini_files)

# generate tag files for each input file
rule all:
    input:
        expand("tag/input_{x}.tag", x=range(0, len(ini_files)))
    output:
        "correlators.done"
    shell:
        "touch {output}"

# run python3 ./fit_correlator.py --ini inis/input_x.ini && touch tag/input_x.tag
# for each input_x.ini in inis/
rule fit_correlator:
    input:
        ini="inis/input_{x}.ini"
    output:
        tag="tag/input_{x}.tag"
    shell:
        "./run_fit.sh {input.ini} {output.tag}"
        # "python3 ./fit_correlator.py -i {input.ini} && touch {output.tag}"

# rule to cleanup
rule clean:
    shell:
        "rm -f tag/*.tag"